<?php

namespace Database\Seeders;

use App\Models\Part;
use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PartSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('parts')->delete();

        $this->call([
            MaterialTypeSeeder::class
        ]);

        Part::create([

            [
                'id' => '10000163',
                'material_description' => 'AMPERE METER,PZ72-AI,ACREL',
                'material_type' => 'V1',
                'qty' => '6',
                'location' => 'LEMARI 1 SLOT A',
            ],
            [
                'id' => '10000227',
                'material_description' => 'VOLT METER,K3MA-J-A2,100-240V',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT B',
            ],
            [
                'id' => '10000966',
                'material_description' => '#BEARING, 6001 2RS',
                'material_type' => 'V1',
                'qty' => '3',
                'location' => 'LEMARI 5 SLOT D',
            ],
            [
                'id' => '10001028',
                'material_description' => '#BEARING, 6203 2RS',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10001030',
                'material_description' => '#BEARING, 6204 2RS',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT E',
            ],
            [
                'id' => '10003439',
                'material_description' => 'PANEL,OPERATOR,6AV6-642-0BA01-1AX1',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10003670',
                'material_description' => 'CABLE SCOON,RING SC,300-16MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10004315',
                'material_description' => 'CAPACITOR,RG-2,SHIZUKI,50KVAR,3PHAS,415V',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'WORKSHOP BAWAH',
            ],
            [
                'id' => '10004394',
                'material_description' => 'CARBON BRUSH,25X32X50MM,NOVOTEX,600KW',
                'material_type' => 'V1',
                'qty' => '12',
                'location' => 'LEMARI 5 SLOT D',
            ],
            [
                'id' => '10004567',
                'material_description' => 'AUTO STAR COUPLER,ASC 25',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 6 SLOT C',
            ],
            [
                'id' => '10004684',
                'material_description' => 'CONTROLLER PROGRAMABLE,FX1/FX3 S-10MR-ES',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10004685',
                'material_description' => 'CONTROLLER PROGRAMABLE,GS2PU 72 AS',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10004686',
                'material_description' => 'CONTROLLER PROGRAMABLE,GS2PU 82,TOSHIBA',
                'material_type' => 'ND',
                'qty' => '3',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10004750',
                'material_description' => 'ENCODER POSITION XMTR,JRQ2-44-R',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10004838',
                'material_description' => 'INPUT ANALOG,GAD 668-S,TOSHIBA',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10004844',
                'material_description' => 'INPUT DIGITAL,GD1 635-S',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10004845',
                'material_description' => 'INPUT DIGITAL,GPI 632-S',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10004865',
                'material_description' => 'MODULE COM.,GEN 651A-S',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10004866',
                'material_description' => 'MODULE COM.,GPF 611-S',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10004912',
                'material_description' => 'NAME GP PROFIBUS I/F,070.PF11 DC',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 6 SLOT C',
            ],
            [
                'id' => '10004917',
                'material_description' => 'OUTPUT ANALOG,GDA 664-S,TOSHIBA',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10004923',
                'material_description' => 'OUTPUT DIGITAL,GDQ 635-S',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10005001',
                'material_description' => 'POWER SUPPLY UNIT,EGD DR-4524',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10005013',
                'material_description' => 'POWER SUPPLY,S82K 01524,INPUT,100-240VAC',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10005020',
                'material_description' => 'POWER SUPPLY,DPP/DRB-120-24,120W,5A,24V',
                'material_type' => 'V1',
                'qty' => '1',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10005021',
                'material_description' => 'POWER SUPPLY,DPP 240-24,10 A,24 V',
                'material_type' => 'V1',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10005028',
                'material_description' => 'POWER SUPPLY,JWS50-24',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10005030',
                'material_description' => 'POWER SUPPLY,LWT50H-5FF,100 – 240 VAC',
                'material_type' => 'ND',
                'qty' => '5',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10005061',
                'material_description' => 'PRINTED CIRCUIT BOARD, 1821.152.020',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT D',
            ],
            [
                'id' => '10005066',
                'material_description' => 'PRINTED WIRING BOARD,ARND-3110N+3620A',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT A',
            ],
            [
                'id' => '10005069',
                'material_description' => 'PRINTED WIRING BOARD,ARND-3119A,TOSHIBA',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 7 SLOT A',
            ],
            [
                'id' => '10005071',
                'material_description' => 'PRINTED WIRING BOARD,ARND-3621B',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT A',
            ],
            [
                'id' => '10005072',
                'material_description' => 'PRINTED WIRING BOARD,ARND-4025 A',
                'material_type' => 'ND',
                'qty' => '10',
                'location' => 'LEMARI 7 SLOT A',
            ],
            [
                'id' => '10005075',
                'material_description' => 'PRINTED WIRING BOARD,ARND-4061A',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT A',
            ],
            [
                'id' => '10005639',
                'material_description' => 'CONTACT CLEANER,SPRAY,2016,CRC',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI KAYU WS ATAS',
            ],
            [
                'id' => '10005672',
                'material_description' => 'RED URETHON SEAL COT,SPRAY,2044,CRC',
                'material_type' => 'V1',
                'qty' => '1',
                'location' => 'LEMARI KAYU WS ATAS',
            ],
            [
                'id' => '10005683',
                'material_description' => 'WD, 40, LIQUID, 412 ML',
                'material_type' => 'V1',
                'qty' => '1',
                'location' => 'LEMARI KAYU WS ATAS',
            ],
            [
                'id' => '10005780',
                'material_description' => 'DP/DP COUPLER,6ES7 158 0AD01 0XA0',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10005782',
                'material_description' => 'F/O MODUL,OZD PROFI 12M G12,HIRSCHMANN',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 6 SLOT C',
            ],
            [
                'id' => '10005825',
                'material_description' => 'CABLE SCOON,RING SC,120-12MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10005827',
                'material_description' => 'CABLE SCOON,RING SC,150-12MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10005828',
                'material_description' => 'CABLE SCOON,RING SC,16-10MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10005829',
                'material_description' => 'CABLE SCOON,RING SC,185-14MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10005835',
                'material_description' => 'CABLE SCOON,RING SC,25-10MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10005838',
                'material_description' => 'CABLE SCOON,RING SC,35-8MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10005840',
                'material_description' => 'CABLE SCOON,RING SC,4-5MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10005842',
                'material_description' => 'CABLE SCOON,RING SC,50-10MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10005843',
                'material_description' => 'CABLE SCOON,RING SC,6MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10005846',
                'material_description' => 'CABLE SCOON,RING SC,70-10MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10005848',
                'material_description' => 'CABLE SCOON,RING SC,95-12MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10005850',
                'material_description' => 'CABLE SCOON,Y,1.25-3MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10005869',
                'material_description' => 'CONECTING,RAIL WHEEL,CRANE KY-BC 3300',
                'material_type' => 'ND',
                'qty' => '5',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10005991',
                'material_description' => 'CONNECTOR,RJ 45',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10006090',
                'material_description' => 'CABLE SCOON,RING SC,10-8MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10006093',
                'material_description' => 'CABLE SCOON,RING SC,240-16MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10006097',
                'material_description' => 'CABLE,SCOON,PIN HOLE,1,5MM,FERRUL',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10006112',
                'material_description' => 'SUBCON PLUS PROFIB,SC2,571151,PHOENIX',
                'material_type' => 'ND',
                'qty' => '14',
                'location' => 'LEMARI 6 SLOT C',
            ],
            [
                'id' => '10006140',
                'material_description' => 'TERMINAL BLOCK, VIKING 4 MM, 371-69/61',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10006178',
                'material_description' => 'CONTACT BLOCK,XENL112/XENG1191,SCHNEIDER',
                'material_type' => 'V1',
                'qty' => '5',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10006213',
                'material_description' => 'CONTACTOR MAGNETIC, S-N 400, 220V',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT D',
            ],
            [
                'id' => '10006215',
                'material_description' => 'CONTACTOR MAGNETIC, S-N 220, 220V',
                'material_type' => 'V1',
                'qty' => '2',
                'location' => 'LEMARI 1 SLOT D',
            ],
            [
                'id' => '10006216',
                'material_description' => 'CONTACTOR MAGNETIC, S-N/T - 100',
                'material_type' => 'V1',
                'qty' => '3',
                'location' => 'LEMARI 1 SLOT D',
            ],
            [
                'id' => '10006217',
                'material_description' => 'CONTACTOR MAGNETIC,S-N125,MITSUBISH,220V',
                'material_type' => 'V1',
                'qty' => '3',
                'location' => 'LEMARI 1 SLOT D',
            ],
            [
                'id' => '10006218',
                'material_description' => 'CONTACTOR MAGNETIC,SN-150(SK),200V-240V',
                'material_type' => 'V1',
                'qty' => '2',
                'location' => 'LEMARI 1 SLOT D',
            ],
            [
                'id' => '10006219',
                'material_description' => 'CONTACTOR MAGNETIC, S/N 180, 220V',
                'material_type' => 'V1',
                'qty' => '2',
                'location' => 'LEMARI 1 SLOT D',
            ],
            [
                'id' => '10006220',
                'material_description' => 'CONTACTOR MAGNETIC, S-N/T - 25',
                'material_type' => 'V1',
                'qty' => '3',
                'location' => 'LEMARI 1 SLOT D',
            ],
            [
                'id' => '10006221',
                'material_description' => 'CONTACTOR MAGNETIC, S-N 300, 220V',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT D',
            ],
            [
                'id' => '10006222',
                'material_description' => 'CONTACTOR MAGNETIC, S-N/T-35, 3P, 220V',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT D',
            ],
            [
                'id' => '10006223',
                'material_description' => 'CONTACTOR MAGNETIC, S-N/T - 50',
                'material_type' => 'V1',
                'qty' => '2',
                'location' => 'LEMARI 1 SLOT D',
            ],
            [
                'id' => '10006224',
                'material_description' => 'CONTACTOR MAGNETIC, S-N/T 65, 240V',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT D',
            ],
            [
                'id' => '10006225',
                'material_description' => 'CONTACTOR MAGNETIC, S-N/T - 80',
                'material_type' => 'V1',
                'qty' => '4',
                'location' => 'LEMARI 1 SLOT D',
            ],
            [
                'id' => '10006239',
                'material_description' => 'CONTACTOR,AUXILIARY,LADN20,TELEMECANIQUE',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10006245',
                'material_description' => 'CONTACTOR,AUXILIARY,LADN40,TELEMECANIQ',
                'material_type' => 'ND',
                'qty' => '4',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10006248',
                'material_description' => 'CONTACTOR, AUXILIARY, LADN-22',
                'material_type' => 'V1',
                'qty' => '20',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10006272',
                'material_description' => 'CONTACTOR,LADN 04,TELEMECANIQUE',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10006275',
                'material_description' => 'CONTACTOR,LC1D09 E7,TELEMECANIQUE,48V',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10006278',
                'material_description' => 'CONTACTOR,LC1D258 F7,1NC + 1NO,110 VAC',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT B',
            ],
            [
                'id' => '10006283',
                'material_description' => 'CONTACTOR,LC1D25 F7,TELEMECANIQUE,110V',
                'material_type' => 'V1',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10006285',
                'material_description' => 'CONTACTOR,LC1D09 F7,TELEMECANIQUE,110V',
                'material_type' => 'V1',
                'qty' => '7',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10006286',
                'material_description' => 'CONTACTOR,LC1D09 D7,SCHNEIDER,50HZ,42V',
                'material_type' => 'V1',
                'qty' => '3',
                'location' => 'LEMARI 4 SLOT B',
            ],
            [
                'id' => '10006287',
                'material_description' => 'CONTACTOR,LC1D09 M7,SCHNEIDER,220V',
                'material_type' => 'V1',
                'qty' => '2',
                'location' => 'LEMARI 1 SLOT D',
            ],
            [
                'id' => '10006290',
                'material_description' => 'CONTACTOR,LC1D18 M7,SCHNEIDER,50HZ,220V',
                'material_type' => 'V1',
                'qty' => '6',
                'location' => 'LEMARI 1 SLOT D',
            ],
            [
                'id' => '10006292',
                'material_description' => 'CONTACTOR,LC1D25 M7,SCHNEIDER,200-220V',
                'material_type' => 'V1',
                'qty' => '2',
                'location' => 'LEMARI 1 SLOT D',
            ],
            [
                'id' => '10006300',
                'material_description' => 'CONTACTOR, LC1D80 F7, 110V',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT B',
            ],
            [
                'id' => '10006301',
                'material_description' => 'CONTACTOR,LC1D80 M7,TELEMECANIQUE',
                'material_type' => 'V1',
                'qty' => '3',
                'location' => 'LEMARI 4 SLOT B',
            ],
            [
                'id' => '10006302',
                'material_description' => 'CONTACTOR,LC1DWK12 M5/7,SCHNEIDER,220V',
                'material_type' => 'V1',
                'qty' => '4',
                'location' => 'LEMARI 1 SLOT D',
            ],
            [
                'id' => '10006310',
                'material_description' => 'CONTACTOR,LC1D258E7,TELEMECANIQ,50HZ,48V',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10006313',
                'material_description' => 'CONTACTOR,MAGNETIC,CAD32F7,SCHNEIDE,110V',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT D',
            ],
            [
                'id' => '10006345',
                'material_description' => 'TIMER ON DELAY,RE48ATM12MW,24-240VAC/DC',
                'material_type' => 'V1',
                'qty' => '5',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10006349',
                'material_description' => 'TIMER,H3CR-A11,OMRON,240 VAC',
                'material_type' => 'ND',
                'qty' => '5',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10006350',
                'material_description' => 'Timer, RE7YR12BU/RE22R2QGMR, 220V',
                'material_type' => 'V1',
                'qty' => '2',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10006352',
                'material_description' => 'TIMER,H3CR-H8L OFF DELAY(MIN),OMRON,240V',
                'material_type' => 'ND',
                'qty' => '5',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10006355',
                'material_description' => 'TIMER, LADR0 0.1-3S 0FF DL,TELEMECANIC',
                'material_type' => 'V1',
                'qty' => '6',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10006358',
                'material_description' => 'TIMER,LADTO,0,1 – 3 SEC,TELEMECANIC',
                'material_type' => 'V1',
                'qty' => '5',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10007669',
                'material_description' => 'FUSE,TABUNG,GLASS,100 MA,250 V',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10007789',
                'material_description' => 'FUSE LINK TYP:CLS 3.6KV/C70A/M100A ',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 5 SLOT B',
            ],
            [
                'id' => '10007816',
                'material_description' => 'FUSE,HIGH SPEED,10URD73TTF1000',
                'material_type' => 'V1',
                'qty' => '11',
                'location' => 'LEMARI 6 SLOT A',
            ],
            [
                'id' => '10007821',
                'material_description' => 'FUSE,HIGH SPEED,9.5URD 273TTF2200,2200A',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 6 SLOT A',
            ],
            [
                'id' => '10007966',
                'material_description' => 'MCB, C 60H C4, 4A, 2P',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10007974',
                'material_description' => 'NFB, NF 250-HW/V, 250A, 3P, 690V',
                'material_type' => 'V1',
                'qty' => '1',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10007981',
                'material_description' => 'NFB, NF 125-HW, 20A, 3P',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10007991',
                'material_description' => 'NFB, NF-250-HW/V, 125A, 3P',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10007993',
                'material_description' => 'NFB, NF 125-HW, 30-32A, 3P',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10007995',
                'material_description' => 'NFB, NF 125-HW, 50A, 3P, 690V',
                'material_type' => 'V1',
                'qty' => '2',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10007996',
                'material_description' => 'NFB, NF 125-HW, 63A, 2P',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10008001',
                'material_description' => 'NFB, NF 160-HW, 160A, 3P,690V',
                'material_type' => 'V1',
                'qty' => '2',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10008004',
                'material_description' => 'NFB, NF 250-HW, 200A, 3P',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10008005',
                'material_description' => 'NFB, NF 250-HW/V, 150A, 3P',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10008009',
                'material_description' => 'NFB, NF 400-SP/SW, 350A, 3P, 690V',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10008010',
                'material_description' => 'NFB, NF 400-SW, 400A, 3P, 690V',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10008884',
                'material_description' => 'HOLDER BRUSH,26 X 10 MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 5 SLOT D',
            ],
            [
                'id' => '10009979',
                'material_description' => 'TRANSMITTER,LTCE-5A-L3/T,0-5A,220V,ATT2',
                'material_type' => 'ND',
                'qty' => '43',
                'location' => 'LEMARI 1 SLOT A',
            ],
            [
                'id' => '10010004',
                'material_description' => 'COUPLING FLEXIBLE,INSULATED,406040-17A',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 6 SLOT B',
            ],
            [
                'id' => '10010055',
                'material_description' => 'ISOLATOR TYPE:DGP3 IN/OUT 0-10VDC/220V',
                'material_type' => 'ND',
                'qty' => '6',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10010152',
                'material_description' => 'SPEED CON,ED MOTOR CONTROL PANEL,S5200',
                'material_type' => 'V1',
                'qty' => '1',
                'location' => 'LEMARI 6 SLOT D',
            ],
            [
                'id' => '10010331',
                'material_description' => 'LAMP PILOT, GREEN, XB4BVM3, 25MM, 220V',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10010332',
                'material_description' => 'LAMP PILOT, RED, XB4BVM4, 25MM, 220V',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10010333',
                'material_description' => 'LAMP PILOT, YELLOW, XB4BVM5, 25MM, 220V',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10010523',
                'material_description' => 'MOTOR SERVO&DRIVE,HC-SFS102,1KW,2000RPM',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 4 SLOT E',
            ],
            [
                'id' => '10010550',
                'material_description' => 'MOTOR,1821.140.010,118W,6,5A,24V,GEFECNE',
                'material_type' => 'V1',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT D',
            ],
            [
                'id' => '10010801',
                'material_description' => 'INVERTER, ELECTRA DRIVE, FR-E720S-030',
                'material_type' => 'V1',
                'qty' => '1',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10011126',
                'material_description' => 'RESOLVER,TS.2025N371E 10D,1KHZ,10V',
                'material_type' => 'V1',
                'qty' => '1',
                'location' => 'LEMARI 6 SLOT B',
            ],
            [
                'id' => '10012556',
                'material_description' => 'SEAL, CUP DST, RUBBER, 15326/274045',
                'material_type' => 'V1',
                'qty' => '10',
                'location' => 'LEMARI 4 SLOT B',
            ],
            [
                'id' => '10014667',
                'material_description' => 'SOCKET TIMER,P2CF-08,H3CR-F8, RUZC2M',
                'material_type' => 'ND',
                'qty' => '30',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10014724',
                'material_description' => 'SOCKET,PYF.14-AN/RXZE2M114M,U/RELAY MY4',
                'material_type' => 'V1',
                'qty' => '40',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10016377',
                'material_description' => 'CURRENT, COLLECTOR, CL7 - 7 - 100',
                'material_type' => 'V1',
                'qty' => '1',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10016380',
                'material_description' => 'CURRENT COLECTOR,DOUBLE,GROUND ,153682',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 4 SLOT B',
            ],
            [
                'id' => '10016381',
                'material_description' => 'CURRENT COLECTOR,DOUBLE,120 PHASE,153681',
                'material_type' => 'V1',
                'qty' => '3',
                'location' => 'LEMARI 4 SLOT B',
            ],
            [
                'id' => '10016428',
                'material_description' => 'RECTIFIER,ESD141,60003098,200-690VAC50HZ',
                'material_type' => 'V1',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10016430',
                'material_description' => 'RECTIFIER, NM181NR4, 60003169, CONE',
                'material_type' => 'V1',
                'qty' => '1',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10016447',
                'material_description' => 'MANUAL STATER,GV2-M07,TELEMEC,1,6-2,5A',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10016449',
                'material_description' => 'MOTOR RELAY,CCR21/CCR22,TOSHIBA,200V',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT D',
            ],
            [
                'id' => '10016456',
                'material_description' => 'OVERLOAD,LRD-08,TELEMECANIQUE,2.5–4A',
                'material_type' => 'ND',
                'qty' => '4',
                'location' => 'LEMARI 1 SLOT B',
            ],
            [
                'id' => '10016503',
                'material_description' => 'POWER FACTOR REG, RVT2-12/V-MS-12Q',
                'material_type' => 'V1',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT D',
            ],
            [
                'id' => '10016571',
                'material_description' => 'RELAY, LY4N/RPM42P7, 220 V',
                'material_type' => 'V1',
                'qty' => '30',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10016584',
                'material_description' => 'RELAY, MY4N/RXM4AB2P7, 220-240 VAC',
                'material_type' => 'V1',
                'qty' => '50',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10016585',
                'material_description' => 'RELAY, MY4N/RXM4AB2BD, 24 VDC',
                'material_type' => 'V1',
                'qty' => '20',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10016629',
                'material_description' => 'SOCKET,PTF 14A-E/RPZF4-U/LY4N,220V',
                'material_type' => 'V1',
                'qty' => '40',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10016640',
                'material_description' => 'SOCKET,OMRON,U/TIMER P2CF-11,100A,250VAC',
                'material_type' => 'ND',
                'qty' => '4',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10018213',
                'material_description' => 'EMERGENCY STOP (PAKAI KUNCI),AH 30/NO+NC',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10018246',
                'material_description' => 'NFB, NF 125-HW/HV, 100A, 3P',
                'material_type' => 'ND',
                'qty' => '3',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10018291',
                'material_description' => 'PROFIBUS,CA5-PFSALL/EX-01,PROFACE',
                'material_type' => 'V1',
                'qty' => '4',
                'location' => 'LEMARI 6 SLOT C',
            ],
            [
                'id' => '10018332',
                'material_description' => 'PUSH BUTTON PILOT LAMP,AH25,XB4BW334,GRN',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10018333',
                'material_description' => 'PUSH BUTTON PILOT LAMP,AH25,XB4BW344,RED',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10018398',
                'material_description' => 'LIMIT SWITCH,WL - NJ,WL 9514M,OMRON',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10018399',
                'material_description' => 'LIMIT SWITCH,WL CA 12,OMRON',
                'material_type' => 'V1',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10018400',
                'material_description' => 'LIMIT SWITCH,WLD2',
                'material_type' => 'ND',
                'qty' => '12',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10018416',
                'material_description' => 'PROXIMITY SWITCH,IFRM08P17A1/L,EMO PR',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10018443',
                'material_description' => 'FLOATLESS LEVEL, SWITCH, 61F-G-AP, 220V',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10018481',
                'material_description' => 'SELECTOR SWITCH,1-0-2,3P,SPRING RETURN',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10018989',
                'material_description' => 'SAKAPHEN',
                'material_type' => 'V1',
                'qty' => '2',
                'location' => 'LEMARI KAYU WS ATAS',
            ],
            [
                'id' => '10019221',
                'material_description' => 'CURRENT TRANSFORMER,CT 70,100/5 A',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT B',
            ],
            [
                'id' => '10019222',
                'material_description' => 'CURRENT TRANSFORMER,CT 70,150/5A',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT B',
            ],
            [
                'id' => '10019223',
                'material_description' => 'CURRENT TRANSFORMER,CT 70,200/5A',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT B',
            ],
            [
                'id' => '10019224',
                'material_description' => 'CURRENT TRANSFORMER,CT 70,250/5A',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT B',
            ],
            [
                'id' => '10019225',
                'material_description' => 'CURRENT TRANSFORMER,CT 70,300/5A',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT B',
            ],
            [
                'id' => '10019270',
                'material_description' => 'CURRENT TRANSFORMER,CT 70,50/5A',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT B',
            ],
            [
                'id' => '10020433',
                'material_description' => 'PRINTED WIRING BOARD,ARND-3110L+3620A',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT A',
            ],
            [
                'id' => '10020519',
                'material_description' => 'MCB, IC60H, 32A, 3P',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10020539',
                'material_description' => 'ETHERNET MOXA,EDS-308-MM-SC 2FO/6PORT',
                'material_type' => 'ND',
                'qty' => '3',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10020592',
                'material_description' => 'THERMAL MCB,GV2-P08,2.5 - 4A',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10020948',
                'material_description' => 'TRANSDUCER CT ,WSK 30,1/5AMP ,2.5VAC',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 6 SLOT A',
            ],
            [
                'id' => '10021322',
                'material_description' => 'TENSION,TRANSMITTER,PFEA111,ABB',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT D',
            ],
            [
                'id' => '10021491',
                'material_description' => 'SWITCH ELEMENT,SES2BE,87455044/33,274550',
                'material_type' => 'V1',
                'qty' => '12',
                'location' => 'LEMARI 4 SLOT B',
            ],
            [
                'id' => '10021992',
                'material_description' => '1ST SHUNT RELEASE,FOR VCB 3 AH 1264-2',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 5 SLOT D',
            ],
            [
                'id' => '10022174',
                'material_description' => 'FUSE,170M7597,BUSSMAN,1500A,1250V',
                'material_type' => 'ND',
                'qty' => '9',
                'location' => 'LEMARI 6 SLOT A',
            ],
            [
                'id' => '10022253',
                'material_description' => 'FUSE,HIGH SPEED,12.5URD2X73TTF0800',
                'material_type' => 'ND',
                'qty' => '4',
                'location' => 'LEMARI 6 SLOT A',
            ],
            [
                'id' => '10022258',
                'material_description' => 'FUSE,HIGH SPEED12URD73TTF0900,900A,1200V',
                'material_type' => 'ND',
                'qty' => '11',
                'location' => 'LEMARI 6 SLOT A',
            ],
            [
                'id' => '10022263',
                'material_description' => 'CABLE SCOON,RING SC,50-14MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10022268',
                'material_description' => 'CABLE SCOON,RING SC,35-10MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10022314',
                'material_description' => 'FUSE,HIGH SPEED,12.5URD2X73TTF1600,1600A',
                'material_type' => 'ND',
                'qty' => '4',
                'location' => 'LEMARI 6 SLOT A',
            ],
            [
                'id' => '10022315',
                'material_description' => 'FUSE,HIGH SPEED,12.5URD2X73TTF1250,1250A',
                'material_type' => 'ND',
                'qty' => '4',
                'location' => 'LEMARI 6 SLOT A',
            ],
            [
                'id' => '10022316',
                'material_description' => 'FUSE,HIGH SPEED,11URD71TTF0500,500A',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 6 SLOT A',
            ],
            [
                'id' => '10022317',
                'material_description' => 'FUSE,HIGH SPEED,6.9URD31TTF0400,400A',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 6 SLOT A',
            ],
            [
                'id' => '10022318',
                'material_description' => 'FUSE,HIGH SPEED,6.9URD31TTF0350,350A',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 6 SLOT A',
            ],
            [
                'id' => '10022393',
                'material_description' => 'MANUAL STARTER,GV2ME14,SCHNEIDER,6-10A',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10022418',
                'material_description' => 'MANUAL STATER,GV2ME10,SCHNEIDER,4-6,3A',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10022590',
                'material_description' => 'EOCR, LT4706M7S, SCHNEIDER, DS3-05S',
                'material_type' => 'V1',
                'qty' => '20',
                'location' => 'LEMARI 1 SLOT B',
            ],
            [
                'id' => '10022591',
                'material_description' => 'EOCR,LT4730M7S,SCHNEIDER,3-30 A',
                'material_type' => 'ND',
                'qty' => '9',
                'location' => 'LEMARI 1 SLOT B',
            ],
            [
                'id' => '10022674',
                'material_description' => 'PUSH BUTTON,XB4BW31M5,WHITE,SCHNEID,220V',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10022675',
                'material_description' => 'PUSH BUTTON,XB4BW33M5,GREEN,SCHNEID,220V',
                'material_type' => 'ND',
                'qty' => '10',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10022676',
                'material_description' => 'PUSH BUTTON,XB4BW34M5,RED,SCHNEID,220V',
                'material_type' => 'ND',
                'qty' => '10',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10022677',
                'material_description' => 'PUSH BUTTON,XB4BW35M5,YELLOW,SCHNEI,220V',
                'material_type' => 'ND',
                'qty' => '10',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10022892',
                'material_description' => 'GATEWAY,UC-7402-PLUS,MOXA,12-48VDC',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10022893',
                'material_description' => 'ETHERNET,EDS-408A-MM-SC 2FO/6PORT,MOXA',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10022894',
                'material_description' => 'ETHERNET,EDS-205A-MM-SC 5PORT,MOXA',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10022968',
                'material_description' => 'PRINTED WIRING BOARD,ARND-4061B',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 7 SLOT A',
            ],
            [
                'id' => '10023058',
                'material_description' => 'FUSE,HIGH SPEED,6.9URD33TTF1000,1000A',
                'material_type' => 'ND',
                'qty' => '4',
                'location' => 'LEMARI 6 SLOT A',
            ],
            [
                'id' => '10023323',
                'material_description' => 'ELECT. POS.TRANS,RWG4020,AUMA',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 6 SLOT B',
            ],
            [
                'id' => '10023329',
                'material_description' => 'CONTACTOR,LC1D25E7,TELEMECANI,50HZ,48VAC',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10023491',
                'material_description' => 'INVERTER,ACS355-03E-15A6-4,7.5KW,ABB',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT E',
            ],
            [
                'id' => '10023595',
                'material_description' => 'FAN,AC,TYPE:20060,8",ORIX,2P,220V"',
                'material_type' => 'V1',
                'qty' => '3',
                'location' => 'LEMARI 5 SLOT A',
            ],
            [
                'id' => '10023767',
                'material_description' => 'FUSE LINK,FPC3-3X25N,TOSHIBA,M100A,3.3KV',
                'material_type' => 'ND',
                'qty' => '3',
                'location' => 'LEMARI 5 SLOT D',
            ],
            [
                'id' => '10023771',
                'material_description' => 'FUSE LINK,CLS,M150A,3.6KV,MITSUBISHI',
                'material_type' => 'ND',
                'qty' => '6',
                'location' => 'LEMARI 5 SLOT B',
            ],
            [
                'id' => '10023835',
                'material_description' => 'ENCODER,OSA18-130,MITSUBISHI',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT E',
            ],
            [
                'id' => '10023836',
                'material_description' => 'DRIVE SERVO,MR-J2S-100A,MITSUBISHI',
                'material_type' => 'V1',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT E',
            ],
            [
                'id' => '10023960',
                'material_description' => 'VOLTAGE SENSOR,SDV-FM2,OMRON,24VDC',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10024055',
                'material_description' => 'KEYPAD,6511,FOR SSD DRIVE 650',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 6 SLOT C',
            ],
            [
                'id' => '10025949',
                'material_description' => 'PROXIMITY SWITCH,PR08-2DP,AUTONICS,24VDC',
                'material_type' => 'V1',
                'qty' => '5',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10025990',
                'material_description' => 'PROTECTION RELAY,GRE120-401A-10-10',
                'material_type' => 'ND',
                'qty' => '4',
                'location' => 'LEMARI 5 SLOT B',
            ],
            [
                'id' => '10026498',
                'material_description' => 'PRINTED WIRING BOARD,ARND-4131A',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT A',
            ],
            [
                'id' => '10026499',
                'material_description' => 'PRINTED WIRING BOARD,ARND-4130A',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT A',
            ],
            [
                'id' => '10026614',
                'material_description' => 'MODULE COM, GPF-612-S, TOSHIBA',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10026633',
                'material_description' => 'MOTOR,SERVO,RML 14CA,KMF, 908-00006',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10026634',
                'material_description' => 'SINAMICS,CU310 DP, 6SL3040-0/1LA00-0AA0',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10026635',
                'material_description' => 'SINAMICS,PM340, 6SL3210-1SE11-7UA0',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10026636',
                'material_description' => 'MICROMASTER 4 EMC FILTER,M-CLEAN',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10026801',
                'material_description' => 'RESOLVER,RTD2A4Y16,10KHZ,4P,BAUMER',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10026876',
                'material_description' => 'PRINTED WIRING BOARD,ARND-4045B,XIO CARD',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT A',
            ],
            [
                'id' => '10026877',
                'material_description' => 'PRINTED WIRING BOARD,ARND-4046A,DISPLAY',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 7 SLOT A',
            ],
            [
                'id' => '10026880',
                'material_description' => 'POWER SUPPLY,MTW60-51515,220V,5,-15,+15V',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10026885',
                'material_description' => 'POWER SUPPLY,LDA30F-24,224V-24VDC,1.3A',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10026886',
                'material_description' => 'FUSE,170M6471,2000A,500V,BUSSMANN',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 6 SLOT A',
            ],
            [
                'id' => '10027730',
                'material_description' => 'PLC, FX3S-14 MR-DS, MELSEC, MITSUBISHI',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10027791',
                'material_description' => 'MODULE,FL-NET COMM,FL612,TOSHIBA',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10027992',
                'material_description' => 'ENCODER,FA-CODER TS5013N156,15VDC,2048',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 6 SLOT B',
            ],
            [
                'id' => '10028209',
                'material_description' => 'COUPLING RESOLVER,TS.2025N371E10D,NM0285',
                'material_type' => 'V1',
                'qty' => '3',
                'location' => 'LEMARI 6 SLOT B',
            ],
            [
                'id' => '10028693',
                'material_description' => 'CONTACTOR, LC1D65AE7, 48VAC, SCHNEIDER',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10028819',
                'material_description' => 'FLOATLESS LEVEL, CONT, 61F-G2, 220V',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 5 SLOT C',
            ],
            [
                'id' => '10028843',
                'material_description' => 'POWER SUPPLY,DR120-48,48VDC',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10029065',
                'material_description' => 'IGBT,2MBI400U4H-170-01,400A,1700V',
                'material_type' => 'ND',
                'qty' => '20',
                'location' => 'LEMARI 7 SLOT D',
            ],
            [
                'id' => '10029207',
                'material_description' => 'TRAFO STEP DOWN,100VA,380V/220V',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10029244',
                'material_description' => 'CAPACITOR,LNXV2G222HSHATG,2200UF,400V',
                'material_type' => 'ND',
                'qty' => '4',
                'location' => 'LEMARI 7 SLOT C',
            ],
            [
                'id' => '10029899',
                'material_description' => 'MODULE,POWER SUPPLY,PS693,TOSHIBA',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT B',
            ],
            [
                'id' => '10029964',
                'material_description' => 'CONTACTOR, LC1D40AE7, 48VAC, SCHNEIDER',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10029965',
                'material_description' => 'CABLE SCOON,RING SC,70-14MM',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI KECIL SLOT 4',
            ],
            [
                'id' => '10029982',
                'material_description' => 'INVERTER,ACS355-03E-05A6-4,1.5KW,ABB',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 4 SLOT E',
            ],
            [
                'id' => '10030523',
                'material_description' => 'TENSION AMPLIFIER,AST 3P,VISHAY',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 7 SLOT C',
            ],
            [
                'id' => '10030600',
                'material_description' => 'SINAMICS,CU320,6SL3054-0AA00/0EH00-1BAO',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10030601',
                'material_description' => 'SINAMICS,BOP20,6SL3055-0AA00-4BA0',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10030602',
                'material_description' => 'SINAMICS,SMC10,6SL3055-0AA00-5AA0/3',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10030603',
                'material_description' => 'SINAMICS,HUB DMC20,6SL3055-0AA00-6AA0/1',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10030628',
                'material_description' => 'POWER METER, PM5350, SCHNEIDER',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT A',
            ],
            [
                'id' => '10030638',
                'material_description' => 'SINAMICS,CHOKE,1P6SE6400-3TC00-4AD2',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10030665',
                'material_description' => 'MANUAL STARTER,GV2ME08,SCHNEIDER,2.5-4A',
                'material_type' => 'ND',
                'qty' => '3',
                'location' => 'LEMARI 1 SLOT C',
            ],
            [
                'id' => '10034373',
                'material_description' => 'FUSE LINK,FPC3-3G25N,TOSHIBA,M200A,3.3KV',
                'material_type' => 'ND',
                'qty' => '3',
                'location' => 'LEMARI 5 SLOT D',
            ],
            [
                'id' => '10034455',
                'material_description' => 'DIGITAL PANEL METER,K3MA-F,AC100-240',
                'material_type' => 'ND',
                'qty' => '3',
                'location' => 'LEMARI 1 SLOT B',
            ],
            [
                'id' => '10034636',
                'material_description' => 'MOTOR CONTROLLER,LTMR08MFM+LTMCU',
                'material_type' => 'ND',
                'qty' => '3',
                'location' => 'LEMARI 1 SLOT B',
            ],
            [
                'id' => '10034704',
                'material_description' => 'CAPACITOR,LNR2G402MSMCTG,4000UF,400V',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 7 SLOT C',
            ],
            [
                'id' => '10034720',
                'material_description' => 'MECHANICAL CONTACT RELAY,MKA-2,42/48V',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 4 SLOT B',
            ],
            [
                'id' => '10034919',
                'material_description' => 'CURRENT TRANSFORMER,LT6CT2001,200A/1A',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT B',
            ],
            [
                'id' => '10034944',
                'material_description' => 'ISOLATOR,KNICK,P-27000 H1',
                'material_type' => 'ND',
                'qty' => '3',
                'location' => 'LEMARI 5 SLOT A',
            ],
            [
                'id' => '10035619',
                'material_description' => 'CARBON BRUSH,5334,12 X 8 X 4.5MM',
                'material_type' => 'ND',
                'qty' => '10',
                'location' => 'LEMARI 4 SLOT D',
            ],
            [
                'id' => '10035653',
                'material_description' => 'BOX MODULE,PFXSP5B10,PROFACE',
                'material_type' => 'ND',
                'qty' => '3',
                'location' => 'LEMARI 6 SLOT C',
            ],
            [
                'id' => '10035654',
                'material_description' => 'PROFIBUS MODULE,PFXZCDEUPF1,PROFACE',
                'material_type' => 'ND',
                'qty' => '3',
                'location' => 'LEMARI 6 SLOT C',
            ],
            [
                'id' => '10035655',
                'material_description' => 'TOUCH MONITOR,PFXSP5500TPD,PROFACE',
                'material_type' => 'ND',
                'qty' => '3',
                'location' => 'LEMARI 6 SLOT C',
            ],
            [
                'id' => '10035690',
                'material_description' => 'PROTECTION RELAY,GRE110-4014-10-10',
                'material_type' => 'ND',
                'qty' => '5',
                'location' => 'LEMARI 5 SLOT D',
            ],
            [
                'id' => '10035772',
                'material_description' => 'FUSE,170M7595,BUSSMANN,2500A,1250V',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 6 SLOT A',
            ],
            [
                'id' => '10035938',
                'material_description' => 'PRINTED WIRING BOARD, ARND-4027B6',
                'material_type' => 'ND',
                'qty' => '3',
                'location' => 'LEMARI 7 SLOT A',
            ],
            [
                'id' => '10035941',
                'material_description' => 'DRIVE DEVICE ADAPTER,USIO21,TOSHIBA',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 6 SLOT C',
            ],
            [
                'id' => '10036016',
                'material_description' => 'DIODE, 5SDD-5128L0003, ABB',
                'material_type' => 'ND',
                'qty' => '4',
                'location' => 'LEMARI 6 SLOT B',
            ],
            [
                'id' => '10036017',
                'material_description' => 'INVERTER, CIMRVT4A000BAA, 3KW, YASKAWA',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT C',
            ],
            [
                'id' => '10036019',
                'material_description' => 'PDM, ARND-8122A, TMEIC',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT A',
            ],
            [
                'id' => '10036178',
                'material_description' => 'MAINTENANCE KITS,EMOIII,OSCILATING,KADAN',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT C',
            ],
            [
                'id' => '10036348',
                'material_description' => 'CAPACITOR,LNKV6402MSEBTG,4000UF,430V',
                'material_type' => 'ND',
                'qty' => '7',
                'location' => 'LEMARI 7 SLOT C',
            ],
            [
                'id' => '10036383',
                'material_description' => 'CAPACITOR,LNXV6402MSMBTG,4000UF,430V',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT C',
            ],
            [
                'id' => '10036394',
                'material_description' => 'CAPACITOR,LNKV6202MTECTG,2000UF,430V',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 7 SLOT C',
            ],
            [
                'id' => '10036421',
                'material_description' => 'SINAMIC,CU250S-2PN,6SL3246-0BA22-1FA0,SI',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT B',
            ],
            [
                'id' => '10036422',
                'material_description' => 'SINAMIC,BOP-2,6SL3255-0AA00-4CA1,SIE',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 1 SLOT B',
            ],
            [
                'id' => '10036536',
                'material_description' => 'DIODE,D2520N22T,V1013,INFINEON',
                'material_type' => 'ND',
                'qty' => '6',
                'location' => 'LEMARI 6 SLOT B',
            ],
            [
                'id' => '10036599',
                'material_description' => 'CONTACTOR,LC1D40A M7,220V,SCHNEIDER',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT B',
            ],
            [
                'id' => '10036808',
                'material_description' => 'SOCKET,PENDANT TROLLEY,3412A 16 PIN,KY-B',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10036931',
                'material_description' => 'IGBT,6MBP50RA120-04,1200V,50A,FUJI',
                'material_type' => 'ND',
                'qty' => '1',
                'location' => 'LEMARI 7 SLOT D',
            ],
            [
                'id' => '10037327',
                'material_description' => 'FUSE, NT00, 100A',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 6 SLOT B',
            ],
            [
                'id' => '10037398',
                'material_description' => 'FUSE, NT00C, 63A',
                'material_type' => 'ND',
                'qty' => '0',
                'location' => 'LEMARI 6 SLOT B',
            ],
            [
                'id' => '10038563',
                'material_description' => 'RECTIFIER,GS 26089484,DEMAG',
                'material_type' => 'ND',
                'qty' => '5',
                'location' => 'LEMARI 4 SLOT B',
            ],
            [
                'id' => '10041536',
                'material_description' => 'CONTACTOR, LC1D80E7, SCHNEIDER',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10041560',
                'material_description' => 'CONTACTOR, LC1D32E7',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10041561',
                'material_description' => 'RELAY SMART, ZELIO SR3B261B',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10041562',
                'material_description' => 'EXTENSION, ZELIO SR3XT141BD',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10041565',
                'material_description' => 'CONTACTOR, LC1D128E7',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT A',
            ],
            [
                'id' => '10041566',
                'material_description' => 'CONTACTOR, LC1D09Q7',
                'material_type' => 'ND',
                'qty' => '2',
                'location' => 'LEMARI 4 SLOT A',
            ],
        ]);
    }
}
